export const FETCH_PRODUCTOS_REQUEST = 'FETCH_PRODUCTOS_REQUEST - [ALL PRODUCTOS]';
export const FETCH_PRODUCTOS_SUCCESS = 'FETCH_PRODUCTOS_SUCCESS - [ALL PRODUCTOS]';
export const FETCH_PRODUCTO_SUCCESS = 'FETCH_PRODUCTO_SUCCESS - [GET PRODUCTO BY ID]';
export const DELETE_PRODUCTO = 'DELETE_PRODUCTO - [DELETE PRODUCTO BY ID]';
